"use client";

import "./globals.css";
import Header from "./components/ui/Header";
import { useState } from "react";
import ConnectWithUsContext from "./context/ConnectWithUsContext";
import Footer from "./components/footer/Footer";

// export const metadata = {
//   title: "Kazkovyi Dim",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  const [isPopupOpened, setIsPopupOpened] = useState(false);

  return (
    <html lang="uk" suppressHydrationWarning={true}>
      <body
      // className={`antialiased`}
      // className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ConnectWithUsContext value={[isPopupOpened, setIsPopupOpened]}>
          <Header />
          <div onClick={() => setIsPopupOpened(false)}>{children}</div>
          <Footer />
        </ConnectWithUsContext>
      </body>
    </html>
  );
}
